### ISSUE TITLE
Examples not working on Motorola X 

### ISSUE THREAD

**Issue by ghost** [AFrame/aframe#15]
I just tried aframe.io on my Motorola X (2nd generation) and the examples don't appear correctly (black screen as you can see in the printscreen, even after a while so not a loading problem). Maybe a lighting problem (as we can see first printscreen a little).

Using:
- Motorola X 2nd generation
- Android 6.0
- Mozilla beta 43.0b10 and Chrome 47.0.2526.83 

![screenshot_20151217-103920](https://cloud.githubusercontent.com/assets/5400381/11866372/fecc919e-a4aa-11e5-8176-d0f16b5b2983.png)
![screenshot_20151217-103937](https://cloud.githubusercontent.com/assets/5400381/11866373/fed07138-a4aa-11e5-9843-c1f543d54db7.png)

**Comment by cvan** [comment]
[Sorry](https://aframe.io/faq/#Is_it_A-Frame_or_aframe_or_aframevr_3F), [wrong repo](https://github.com/aframevr/aframe/) - could you file at https://github.com/aframevr/aframe/issues/new instead? Thanks! (Sorry, @AFrame!)
