### ISSUE TITLE
No exit button in VR mode on mobile

### ISSUE THREAD

**Issue by ghost** [AFrame/aframe#16]
When entering the VR mode on mobile, putting it back in portrait doesn't change anything, and there are no "exit VR" button, which makes it a bit difficult to exit VR on phones with no physical back button (in my case Motorola X 2nd gen)

**Comment by cvan** [comment]
[Sorry](https://aframe.io/faq/#Is_it_A-Frame_or_aframe_or_aframevr_3F), [wrong repo](https://github.com/aframevr/aframe/) - could you file at https://github.com/aframevr/aframe/issues/new instead? Thanks! (Sorry, @AFrame!)
